require 'hotel_reservation/hotel'
require 'hotel_reservation/namer'
require 'hotel_reservation/ratinger'
require 'hotel_reservation/integer_rank'
require 'hotel_reservation/set_rates_use_case'
require 'hotel_reservation/set_rates_use_case_request'
require 'hotel_reservation/regular_customer'
require 'hotel_reservation/rewarded_customer'
require 'hotel_reservation/regular_customer_factory'
require 'hotel_reservation/rewarded_customer_factory'
require 'hotel_reservation/rates.rb'
require 'hotel_reservation/rates_factory.rb'
require 'hotel_reservation/applicability_filter.rb'
require 'hotel_reservation/hotel_date.rb'

